import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LanguageProvider } from "@/context/LanguageContext";
import SplashScreen from "@/components/SplashScreen";
import { Analytics } from "@vercel/analytics/next"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Web Developer Terrace BC | Full Stack Developer | LGC Tech",
  description:
    "Professional full-stack web developer in Terrace BC offering custom web design, e-commerce solutions, mobile app development, and UI/UX design. Specializing in React, Next.js, Supabase, and Tailwind CSS for modern business websites.",
  keywords: [
    "web developer Terrace BC",
    "full stack developer Terrace",
    "web design Terrace BC",
    "custom website design",
    "React developer",
    "Next.js developer",
    "e-commerce development",
    "mobile app development",
    "UI/UX design Terrace",
    "web development services",
    "business website design",
    "responsive web design",
    "JavaScript developer",
    "TypeScript",
    "Tailwind CSS",
    "Supabase development",
    "freelance web developer",
    "website redesign Terrace",
    "landing page design",
    "web application development",
    "Terrace BC tech",
  ],
  authors: [{ name: "Lucas Gerhardt de Camargo" }],
  creator: "Lucas Gerhardt de Camargo",
  metadataBase: new URL("https://lgctech.net"),
  alternates: {
    canonical: "https://lgctech.net",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://lgctech.net",
    siteName: "LGC Tech - Web Development",
    title: "Web Developer Terrace BC | Full Stack Development Services",
    description:
      "Expert full-stack web developer in Terrace BC creating modern, responsive websites and web applications. Custom solutions for businesses.",
    images: [
      {
        url: "https://lgctech.net/og-image.png",
        width: 1200,
        height: 630,
        alt: "LGC Tech - Professional Web Development in Terrace BC",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Web Developer Terrace BC - Full Stack Solutions",
    description:
      "Custom web design and development services for Terrace BC businesses. React, Next.js, and modern web technologies.",
    creator: "@lgctechcoder",
    images: ["https://lgctech.net/og-image.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  manifest: "/manifest.json",
  verification: {
    google: "your-google-verification-code",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `document.documentElement.style.colorScheme = 'light';`,
          }}
        />
        {/* Favicon Links - Generated by Favicomatic */}
        <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/apple-touch-icon-57x57.png" />
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114x114.png" />
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72x72.png" />
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144x144.png" />
        <link rel="apple-touch-icon-precomposed" sizes="60x60" href="/apple-touch-icon-60x60.png" />
        <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/apple-touch-icon-120x120.png" />
        <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/apple-touch-icon-76x76.png" />
        <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/apple-touch-icon-152x152.png" />
        <link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196" />
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32" />
        <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16" />
        <link rel="icon" type="image/png" href="/favicon-128.png" sizes="128x128" />
        <meta name="msapplication-TileColor" content="#0B1E3F" />
        <meta name="msapplication-TileImage" content="/mstile-144x144.png" />
        <meta name="msapplication-square70x70logo" content="/mstile-70x70.png" />
        <meta name="msapplication-square150x150logo" content="/mstile-150x150.png" />
        <meta name="msapplication-wide310x150logo" content="/mstile-310x150.png" />
        <meta name="msapplication-square310x310logo" content="/mstile-310x310.png" />
        {/* JSON-LD Structured Data - Person/Professional */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Person",
              "@id": "https://lgctech.net",
              name: "Lucas Gerhardt de Camargo",
              url: "https://lgctech.net",
              jobTitle: "Full Stack Web Developer",
              worksFor: {
                "@type": "Organization",
                name: "LGC Tech",
              },
              sameAs: [
                "https://www.instagram.com/lgctechcoder",
                "https://github.com/camarguin",
              ],
              location: {
                "@type": "City",
                name: "Terrace",
                "@id": "https://en.wikipedia.org/wiki/Terrace,_British_Columbia",
              },
              address: {
                "@type": "PostalAddress",
                addressLocality: "Terrace",
                addressRegion: "BC",
                addressCountry: "CA",
              },
              knowsAbout: [
                "Web Development",
                "Full Stack Development",
                "React",
                "Next.js",
                "TypeScript",
                "JavaScript",
                "Supabase",
                "Firebase",
                "Tailwind CSS",
                "UI/UX Design",
                "E-commerce Development",
                "Mobile App Development",
                "Web Design",
                "Node.js",
              ],
            }),
          }}
        />
        {/* JSON-LD Structured Data - LocalBusiness */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "LocalBusiness",
              "@id": "https://lgctech.net",
              name: "LGC Tech - Web Development",
              description: "Professional web development, design, and mobile app development services in Terrace BC",
              url: "https://lgctech.net",
              telephone: "+17783183796",
              areaServed: [
                {
                  "@type": "City",
                  name: "Terrace",
                  "@id": "https://en.wikipedia.org/wiki/Terrace,_British_Columbia",
                },
                {
                  "@type": "State",
                  name: "British Columbia",
                },
              ],
              address: {
                "@type": "PostalAddress",
                addressLocality: "Terrace",
                addressRegion: "BC",
                addressCountry: "CA",
              },
              serviceType: [
                "Web Development",
                "Web Design",
                "E-Commerce Development",
                "Mobile App Development",
                "UI/UX Design",
                "Landing Page Design",
                "Custom Website Design",
              ],
              priceRange: "$$",
              sameAs: [
                "https://www.instagram.com/lgctechcoder",
                "https://github.com/camarguin",
              ],
            }),
          }}
        />
        {/* JSON-LD Structured Data - Organization */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "LGC Tech",
              url: "https://lgctech.net",
              logo: "https://lgctech.net/logo.png",
              description: "Full-stack web development and design services offering custom websites, e-commerce solutions, and mobile app development.",
              sameAs: [
                "https://www.instagram.com/lgctechcoder",
                "https://github.com/camarguin",
              ],
              contactPoint: {
                "@type": "ContactPoint",
                contactType: "Customer Service",
                email: "contact@lgctech.net",
                telephone: "+17783183796",
              },
            }),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
      >
        <SplashScreen />
        <LanguageProvider>
          {children}
        </LanguageProvider>
        <Analytics />
      </body>
    </html>
  );
}
