import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LanguageProvider } from "@/context/LanguageContext";
import SplashScreen from "@/components/SplashScreen";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lucas Gerhardt - Full Stack Web Developer | Terrace BC",
  description:
    "Experienced full-stack web developer in Terrace BC specializing in React, Next.js, Firebase, and TypeScript. Building modern, responsive web applications and mobile solutions.",
  keywords: [
    "web developer",
    "full stack developer",
    "React developer",
    "Next.js developer",
    "Terrace BC",
    "web development",
    "JavaScript",
    "TypeScript",
    "UI/UX design",
    "firebase",
    "frontend developer",
  ],
  authors: [{ name: "Lucas Gerhardt de Camargo" }],
  creator: "Lucas Gerhardt de Camargo",
  metadataBase: new URL("https://lgctech.net"),
  alternates: {
    canonical: "https://lgctech.net",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://lgctech.net",
    siteName: "LGC Tech",
    title: "Lucas Gerhardt - Full Stack Web Developer | Terrace BC",
    description:
      "Expert full-stack web developer building modern digital experiences with React, Next.js, and cutting-edge technologies.",
    images: [
      {
        url: "https://lgctech.net/og-image.png",
        width: 1200,
        height: 630,
        alt: "LGC Tech - Web Development Portfolio",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Lucas Gerhardt - Full Stack Web Developer",
    description:
      "Building modern web applications with React, Next.js, and Firebase",
    creator: "@lucasgcoder",
    images: ["https://lgctech.net/og-image.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `document.documentElement.style.colorScheme = 'light';`,
          }}
        />
        {/* Favicon Links - Generated by Favicomatic */}
        <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/apple-touch-icon-57x57.png" />
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114x114.png" />
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72x72.png" />
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144x144.png" />
        <link rel="apple-touch-icon-precomposed" sizes="60x60" href="/apple-touch-icon-60x60.png" />
        <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/apple-touch-icon-120x120.png" />
        <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/apple-touch-icon-76x76.png" />
        <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/apple-touch-icon-152x152.png" />
        <link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196" />
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32" />
        <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16" />
        <link rel="icon" type="image/png" href="/favicon-128.png" sizes="128x128" />
        <meta name="msapplication-TileColor" content="#0B1E3F" />
        <meta name="msapplication-TileImage" content="/mstile-144x144.png" />
        <meta name="msapplication-square70x70logo" content="/mstile-70x70.png" />
        <meta name="msapplication-square150x150logo" content="/mstile-150x150.png" />
        <meta name="msapplication-wide310x150logo" content="/mstile-310x150.png" />
        <meta name="msapplication-square310x310logo" content="/mstile-310x310.png" />
        {/* JSON-LD Structured Data - Person/Professional */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Person",
              "@id": "https://lgctech.net",
              name: "Lucas Gerhardt de Camargo",
              url: "https://lgctech.net",
              jobTitle: "Full Stack Web Developer",
              worksFor: {
                "@type": "Organization",
                name: "LGC Tech",
              },
              sameAs: [
                "https://www.instagram.com/lucasgcoder",
                "https://github.com/camarguin",
              ],
              location: {
                "@type": "City",
                name: "Terrace",
              },
              knowsAbout: [
                "Web Development",
                "React",
                "Next.js",
                "TypeScript",
                "JavaScript",
                "Firebase",
                "UI/UX Design",
                "Full Stack Development",
                "Tailwind CSS",
                "Node.js",
              ],
            }),
          }}
        />
        {/* JSON-LD Structured Data - Organization */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "LGC Tech",
              url: "https://lgctech.net",
              logo: "https://lgctech.net/logo.png",
              description: "Full-stack web development services",
              sameAs: [
                "https://www.instagram.com/lucasgcoder",
                "https://github.com/camarguin",
              ],
              contactPoint: {
                "@type": "ContactPoint",
                contactType: "Customer Service",
                email: "contact@lgctech.net",
              },
            }),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
      >
        <SplashScreen />
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
